# Generated by Django 4.1.1 on 2022-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0003_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='unknown_user.jpg', upload_to='user/images'),
        ),
    ]
