# Generated by Django 4.1.1 on 2022-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0004_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='user/images/unknown_user.jpg', upload_to='user/images'),
        ),
    ]
