# Generated by Django 4.1.1 on 2022-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0006_remove_customuser_img_customuser_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img_src',
            field=models.ImageField(default='', upload_to='user/images'),
        ),
    ]
