# Generated by Django 4.1.1 on 2022-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0007_alter_customuser_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=122)),
                ('section', models.CharField(max_length=2)),
                ('photo', models.ImageField(upload_to='uploads/pics')),
                ('caption', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img_src',
            field=models.ImageField(default='media/user/images/unknown_user.jpg', upload_to='user/images'),
        ),
    ]
