# Generated by Django 4.1.1 on 2022-10-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0008_photoupload_alter_customuser_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
