# Generated by Django 4.1.1 on 2022-10-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0009_alter_photoupload_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupload',
            name='user_img_url',
            field=models.CharField(default='media/user/images/unknown_user.jpg', max_length=122),
        ),
    ]
