# Generated by Django 4.1.1 on 2022-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenting_user_url',
            field=models.CharField(default='', max_length=122),
        ),
    ]
