# Generated by Django 4.1.1 on 2022-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0012_comments_commenting_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replies',
            field=models.CharField(default='', max_length=500),
        ),
    ]
