# Generated by Django 4.1.1 on 2022-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0014_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.CharField(default='', max_length=252),
        ),
    ]
