# Generated by Django 4.1.1 on 2022-10-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0015_alter_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
