# Generated by Django 4.1.1 on 2022-10-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0017_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='by_user',
        ),
    ]
