# Generated by Django 4.1.1 on 2022-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0018_remove_notification_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
