# Generated by Django 4.1.1 on 2022-11-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0020_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(default=''),
        ),
    ]
