# Generated by Django 4.1.1 on 2022-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0021_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_img_src',
            field=models.TextField(default=''),
        ),
    ]
