# Generated by Django 4.1.1 on 2022-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0024_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='photo_id',
            field=models.IntegerField(default=0),
        ),
    ]
