# Generated by Django 4.1.1 on 2022-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0025_alter_photoupload_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
